# Generated by Django 5.1.5 on 2025-01-30 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_alter_student_admission_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_date', models.CharField(blank=True, max_length=50, null=True)),
                ('stud_name', models.CharField(blank=True, max_length=100, null=True)),
                ('rs', models.CharField(blank=True, max_length=100, null=True)),
                ('std', models.CharField(blank=True, max_length=30, null=True)),
                ('tot_amount_due', models.CharField(blank=True, max_length=30, null=True)),
                ('amount_recived', models.CharField(blank=True, max_length=30, null=True)),
                ('balance_due', models.CharField(blank=True, max_length=30, null=True)),
                ('payment_received_in', models.CharField(blank=True, max_length=150, null=True)),
                ('received_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
