# Generated by Django 5.1.5 on 2025-01-30 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0003_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='sr',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
