# Generated by Django 5.1.5 on 2025-06-14 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0004_receipt_sr'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
