# Generated by Django 5.1.5 on 2025-07-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0005_student_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='fees_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='paid_months',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
