# Generated by Django 5.1.5 on 2025-07-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0006_student_fees_type_student_paid_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='starting_month',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
