# Generated by Django 5.1.5 on 2025-07-30 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0007_student_starting_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='paid_months',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
